# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  mypy:
    resource_class: small
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "Install pip packages"
          command: "cd server && pip3 install -r requirements.txt"
      - run:
          name: "Run mypy"
          command: "cd server && mypy ./src"
  
  tsc:
    resource_class: small
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: "Install npm packages"
          command: "cd client && npm install"
      - run:
          name: "Run tsc"
          command: "cd client && npm run check"

workflows:
  server:
    jobs:
      - mypy

  client:
    jobs:
      - tsc
