# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  prisma:
    resource_class: small
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "Install Prisma CLI"
          command: "pip3 install prisma"
      - run:
          name: "Validate prisma schema"
          command: "cd db && prisma validate"
    environment:
      DATABASE_URL: "postgres://user:password@127.0.0.1:5432/database"

  pyright:
    resource_class: small
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "Install pip packages"
          command: "cd server && pip3 install -r requirements.txt"
      - run:
          name: "Generate Prisma definitions"
          command: "cd db && prisma generate"
      - run:
          name: "Run pyright"
          command: "cd server && pyright ."

  tsc:
    resource_class: small
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: "Install npm packages"
          command: "cd client && npm install"
      - run:
          name: "Run tsc"
          command: "cd client && npm run check"

workflows:
  server:
    jobs:
      - prisma
      - pyright

  client:
    jobs:
      - tsc
