services:
  postgres-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ppdb_admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ppdb
    ports:
       - "5432:5432"
